Club.create(name: 'Avangard-Energiya', country_code: 'UA', league_name: "Ukrainian Reg Div - Vinnyts'ka oblast - 1D")
Club.create(name: 'Avangard-Promrynok', country_code: 'UA', league_name: 'Ukrainian Lower Division')
Club.create(name: 'Avantas', country_code: 'GR', league_name: 'Greek Amateur Division - Evros')
Club.create(name: 'Avanti Stekene', country_code: 'BE', league_name: 'Belgian Third Amateur Division')
Club.create(name: 'Avântul Albeşti', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Baia-de-Fier', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Bârsana', country_code: 'RO', league_name: 'Romanian Fourth League Maramureş North')
Club.create(name: 'Avântul Comana', country_code: 'RO', league_name: 'Romanian Lower League')
Club.create(name: 'Avântul Drăgăneşti', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Dumbrăviţa', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Floreşti', country_code: 'RO', league_name: 'Romanian Fourth League Giurgiu Seria Nord')
Club.create(name: 'Avântul Golăieşti', country_code: 'RO', league_name: 'Romanian Lower League')
Club.create(name: 'Avântul Ilieni', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Măneciu', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Miheşu', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Periam', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Reghin', country_code: 'RO', league_name: 'Romanian Third League')
Club.create(name: 'Avântul Vânători', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avântul Zărneşti', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Avarta', country_code: 'DK', league_name: 'Danish Second Division')
Club.create(name: 'Avaza', country_code: 'GE', league_name: 'Georgian Lower League')
Club.create(name: 'Avaza 1970', country_code: 'GE', league_name: '-')
Club.create(name: 'AVC Luctor et Emergo', country_code: 'NL', league_name: 'Dutch Tweede Klasse Zondag J')
Club.create(name: 'Avcılar Bld.', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Avedøre', country_code: 'DK', league_name: "Denmark's Series")
Club.create(name: 'Avelarense', country_code: 'PT', league_name: 'Portuguese Lower Regional Divisions')
Club.create(name: 'Avelarense Under 19s', country_code: 'PT', league_name: 'Portugal U19 Lower Divisions')
Club.create(name: 'Aveley', country_code: 'GB', league_name: 'English Isthmian League First Division North')
Club.create(name: 'Avelgem', country_code: 'BE', league_name: 'West-Flanders Provincial Division')
Club.create(name: 'Avellino', country_code: 'IT', league_name: 'Italian Serie B')
Club.create(name: 'Avenir Beggen', country_code: 'LU', league_name: 'Luxembourg Promotion Division')
Club.create(name: 'Avenir Coulongeois', country_code: 'FR', league_name: 'French Regional Divisions')
Club.create(name: 'Avenir de Theix', country_code: 'FR', league_name: 'French Regional Divisions')
Club.create(name: 'Avenir Fonsorbais', country_code: 'FR', league_name: 'French Regional Divisions')
Club.create(name: 'Avenir Foot Lozère', country_code: 'FR', league_name: 'French National 3 - Occitanie')
Club.create(name: 'Avenir Sportif Mouzon', country_code: 'FR', league_name: 'French Regional Divisions')
Club.create(name: 'Aventa-2000', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Avenue Utd', country_code: 'GB', league_name: 'Irish Clare Premier Division')
Club.create(name: 'Averbode', country_code: 'BE', league_name: 'Brabant Provincial Division')
Club.create(name: 'Averøykameratene', country_code: 'NO', league_name: 'Norwegian Lower Division')
Club.create(name: 'Averøykameratene 2', country_code: 'NO', league_name: '-')
Club.create(name: 'Aversa Normanna', country_code: 'IT', league_name: 'Italian Serie D')
Club.create(name: 'Aves', country_code: 'PT', league_name: 'Portuguese Premier League')
Club.create(name: 'Avesta AIK', country_code: 'SE', league_name: 'Swedish Fourth Division')
Club.create(name: 'Avetrana', country_code: 'IT', league_name: 'Italian Eccellenza Puglia')
Club.create(name: 'Avezzano', country_code: 'IT', league_name: 'Italian Serie D')
Club.create(name: 'Avia', country_code: 'GR', league_name: 'Greek Amateur Division - Messinia')
Club.create(name: 'Avià', country_code: 'ES', league_name: 'Spanish Primera Catalana Gr. 1')
Club.create(name: 'Avia Świdnik', country_code: 'PL', league_name: 'Polish Third Division')
Club.create(name: 'Aviator', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Aviator Aktobe', country_code: 'KZ', league_name: 'Kazakhstan Lower League')
Club.create(name: 'Aviator Taldykorgan', country_code: 'KZ', league_name: 'Taldykorgan Championship')
Club.create(name: 'Aviemore Thistle', country_code: 'GB', league_name: 'Scottish Amateur Leagues')
Club.create(name: 'Avigliano', country_code: 'IT', league_name: 'Italian Promozione Basilicata')
Club.create(name: 'Ávila', country_code: 'ES', league_name: 'Spanish Third Division')
Club.create(name: 'Avilés', country_code: 'ES', league_name: 'Spanish Third Division')
Club.create(name: 'Avilés B', country_code: 'ES', league_name: 'Spanish Regional Preferente Asturias')
Club.create(name: 'Avintes', country_code: 'PT', league_name: 'Portuguese Porto Elite Division Serie 1')
Club.create(name: 'Avîntul Bragadiru', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Aviron Bayonnais', country_code: 'FR', league_name: 'French National 3 - Nouvelle Aquitaine')
Club.create(name: 'Avis Arcevia', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Avis Montecalvo', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'AVIS Ripatransone', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Avisma', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Avlida', country_code: 'GR', league_name: 'Greek Amateur Division - Evoia')
Club.create(name: 'Avlonari', country_code: 'GR', league_name: 'Greek Amateur Division - Evoia')
Club.create(name: 'Avoch', country_code: 'GB', league_name: 'Scottish Amateur Leagues')
Club.create(name: 'Avoine-Chinon', country_code: 'FR', league_name: 'French National 3 - Centre Val de Loire')
Club.create(name: 'Avola', country_code: 'IT', league_name: 'Italian Eccellenza Sicilia Grp.B')
Club.create(name: 'Avondale', country_code: 'GB', league_name: 'Irish Regional Level 3')
Club.create(name: 'Avtodor', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Avtodor Smolensk', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Avtomobilist Turan', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Avtomobilist Yuzhno-Sakhalinsk', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Avtosvit', country_code: 'UA', league_name: 'Ukrainian Lower Division')
Club.create(name: 'Avtosvit-2', country_code: 'UA', league_name: 'Ukrainian Lower Division')
Club.create(name: 'Avtozapchast', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: "AVW'66", country_code: 'NL', league_name: 'Lower Leagues')
Club.create(name: 'Axbergs IF', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'Axel FC', country_code: 'NL', league_name: 'Dutch Tweede Klasse Zaterdag E')
Club.create(name: 'Axintele', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Axintele II', country_code: 'RO', league_name: 'Romanian Lower League')
Club.create(name: 'Axiopolis', country_code: 'RO', league_name: 'Romanian Third League')
Club.create(name: 'Axminster', country_code: 'GB', league_name: '-')
Club.create(name: 'Axvalls IF', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'Axys Zola', country_code: 'IT', league_name: 'Italian Eccellenza Emilia-Romagna Grp.A')
Club.create(name: 'Ay-Danil Gaspra', country_code: 'RU', league_name: 'Crimean Lower Division')
Club.create(name: 'Ayamonte', country_code: 'ES', league_name: 'Spanish Primera Andaluza Gr. 1')
Club.create(name: 'Ayancık Bld.', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Ayancık Spor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Ayazağaspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Aybastıspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Aydın Bereketlispor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Aydın DSİ', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Aydın Yıldızspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Aydınkonakspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Aydınlıkevler', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Aydınpınarspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Aydınspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Aydınspor 1923', country_code: 'TR', league_name: 'Turkish 3. League')
Club.create(name: 'Aydıntepe Bld.', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Aygreville', country_code: 'IT', league_name: 'Italian Eccellenza Piemonte Grp.A')
Club.create(name: 'Aylesbury', country_code: 'GB', league_name: 'English Southern League First Division East')
Club.create(name: 'Aylesbury Utd', country_code: 'GB', league_name: 'English Southern League First Division East')
Club.create(name: 'Aylestone Park', country_code: 'GB', league_name: 'Lower Leagues')
Club.create(name: 'Aypi Gençlikspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Ayr', country_code: 'GB', league_name: 'Ladbrokes League 1')
Club.create(name: 'Ayrfield Utd', country_code: 'GB', league_name: 'Irish Dublin AUL Premier A Division')
Club.create(name: 'Ayrón', country_code: 'ES', league_name: 'Spanish Regional Preferente Cantabria')
Club.create(name: 'Aystetten', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Ayvalık Adaspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Ayvalık Sakaryaspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Ayvalıkgücü Bld.', country_code: 'TR', league_name: 'Turkish Regional Amateur League')
Club.create(name: 'Aywaille', country_code: 'BE', league_name: 'Belgian Third Amateur Division')
Club.create(name: 'AZ', country_code: 'NL', league_name: 'Eredivisie')
Club.create(name: 'AZ 2002', country_code: 'BE', league_name: 'Brabant Provincial Division')
Club.create(name: 'Azalea BK', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'AZC Zutphen', country_code: 'NL', league_name: 'Dutch Tweede Klasse Zondag I')
Club.create(name: 'Azech SF', country_code: 'SE', league_name: 'Swedish Fourth Division')
Club.create(name: 'Azeglio', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'AziiaTekhStroi', country_code: 'KZ', league_name: "Ural'sk Championship")
Club.create(name: 'Azkoyen', country_code: 'ES', league_name: 'Spanish Regional Preferente Navarra Gr. 2')
Club.create(name: 'Azov', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Azovets Berdyansk', country_code: 'UA', league_name: 'Ukrainian Lower Division')
Club.create(name: 'Azovets Genichesk', country_code: 'UA', league_name: 'Ukrainian Lower Division')
Club.create(name: 'Azovets P-A', country_code: 'RU', league_name: 'Russian Lower Division')
Club.create(name: 'Azovstal', country_code: 'UA', league_name: 'Ukrainian Lower Division')
Club.create(name: 'AZSV', country_code: 'NL', league_name: 'Dutch Hoofdklasse Zaterdag B')
Club.create(name: 'Azuaga', country_code: 'ES', league_name: 'Spanish Third Division')
Club.create(name: 'Azul e Ouro', country_code: 'PT', league_name: 'Portuguese Lower Regional Divisions')
Club.create(name: 'Azuqueca', country_code: 'ES', league_name: 'Spanish Third Division')
Club.create(name: 'Azur', country_code: 'IL', league_name: 'Israeli A League')
Club.create(name: 'Azzanì', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzano Grassobbio', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzurra', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzurra Due Carrare', country_code: 'IT', league_name: 'Italian Promozione Veneto Grp.C')
Club.create(name: 'Azzurra Monserrato', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzurra Premariacco', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzurra S.Bartolomeo', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzurra Sandrigo', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Azzurri Bienne', country_code: 'CH', league_name: 'Swiss Lower Division')
Club.create(name: 'B 1903', country_code: 'DK', league_name: 'Danish Lower Division')
Club.create(name: 'B 1908', country_code: 'DK', league_name: "Denmark's Series")
Club.create(name: 'B 1909', country_code: 'DK', league_name: "Denmark's Series")
Club.create(name: 'B 1913', country_code: 'DK', league_name: "Denmark's Series")
Club.create(name: 'B 1973 Herlev', country_code: 'DK', league_name: 'Danish Lower Division')
Club.create(name: 'B 52/AFC', country_code: 'DK', league_name: 'Danish Lower Division')
Club.create(name: 'B 73 Slagelse', country_code: 'DK', league_name: 'Danish Lower Division')
Club.create(name: 'B 77', country_code: 'DK', league_name: 'Danish Lower Division')
Club.create(name: 'B 93', country_code: 'DK', league_name: 'Danish Second Division')
Club.create(name: 'B. Karşıyakaspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'B. Merinosspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'B. Özgüzelderespor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'B. Pansu Şekerspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'B. Petrolspor', country_code: 'TR', league_name: 'Turkish 3. League')
Club.create(name: 'B.B.O.B.', country_code: 'GB', league_name: 'Northern Irish North West Junior Premier Division')
Club.create(name: 'B.M. Adaspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'B36', country_code: 'FO', league_name: 'Faroese Premier League')
Club.create(name: 'B36 2', country_code: 'FO', league_name: 'Faroese First Division')
Club.create(name: 'B68', country_code: 'FO', league_name: 'Faroese First Division')
Club.create(name: 'B68 2', country_code: 'FO', league_name: 'Faroese Second Division')
Club.create(name: 'B71', country_code: 'FO', league_name: 'Faroese Second Division')
Club.create(name: 'Baal', country_code: 'BE', league_name: 'Brabant Provincial Division')
Club.create(name: 'Baar', country_code: 'CH', league_name: 'Swiss Lower Division')
Club.create(name: 'Babadag', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Babaeskispor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Băban Marcel', country_code: 'RO', league_name: '-')
Club.create(name: 'Babaros Sefaspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Babberich', country_code: 'NL', league_name: 'Lower Leagues')
Club.create(name: 'Babelsberg', country_code: 'DE', league_name: 'German Regional Division')
Club.create(name: 'Babi', country_code: 'MK', league_name: 'Macedonian Lower Leagues (FYR)')
Club.create(name: 'Băbiciu', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Babite', country_code: 'LV', league_name: 'Latvian Lower Leagues')
Club.create(name: 'Babócsa SE', country_code: 'HU', league_name: 'Hungarian Lower Division')
Club.create(name: 'Babrungas', country_code: 'LT', league_name: 'Lithuanian Lower Leagues')
Club.create(name: 'Babţa', country_code: 'RO', league_name: 'Romanian Fourth League')
Club.create(name: 'Baby Brazil', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bacigalupo', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bacinci', country_code: 'RS', league_name: 'Serbian Lower League')
Club.create(name: 'Backa', country_code: 'RS', league_name: 'Serbian SuperLeague')
Club.create(name: 'Backa (P)', country_code: 'RS', league_name: 'Serbian Zone League')
Club.create(name: 'Backa 1901', country_code: 'RS', league_name: 'Serbian Second League')
Club.create(name: 'Bäckhammars SK', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'Backnang', country_code: 'DE', league_name: 'German Div. Lower')
Club.create(name: 'Bäckseda IF', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'Bácsalmás', country_code: 'HU', league_name: 'Hungarian Lower Division')
Club.create(name: 'Bacup', country_code: 'GB', league_name: 'Lower Leagues')
Club.create(name: 'Bad Abbach', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Bentheim', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Breisig', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Dürrheim', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Grönenbach', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Hersfeld', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Homburg', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Honnef', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Kreuznach', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Langensalza', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Pyrmont', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Ragaz', country_code: 'CH', league_name: 'Swiss Lower Division')
Club.create(name: 'Bad Soden', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Vilbel', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Bad Westernkotten', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Badajoz', country_code: 'ES', league_name: 'Spanish Second Division B4')
Club.create(name: 'Badalasco', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Badalona', country_code: 'ES', league_name: 'Spanish Second Division B3')
Club.create(name: 'Baden', country_code: 'CH', league_name: 'Swiss First League Classic Group 2')
Club.create(name: 'Badesi', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Badesse', country_code: 'IT', league_name: 'Italian Eccellenza Toscana Grp.B')
Club.create(name: 'Badia Polesine', country_code: 'IT', league_name: 'Italian Promozione Veneto Grp.A')
Club.create(name: 'Badnjevac', country_code: 'RS', league_name: 'Serbian Lower League')
Club.create(name: 'Badoere', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Badolato', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Badshot Lea', country_code: 'GB', league_name: 'Lower Leagues')
Club.create(name: 'Bækkelaget', country_code: 'NO', league_name: 'Norwegian Lower Division')
Club.create(name: 'Bækkelaget 2', country_code: 'NO', league_name: '-')
Club.create(name: 'Baena At.', country_code: 'ES', league_name: 'Spanish Primera Andaluza Gr. 2')
Club.create(name: 'Bærum', country_code: 'NO', league_name: 'Norwegian Second Division Group 1')
Club.create(name: 'Bærum 2', country_code: 'NO', league_name: 'Norwegian Lower Division')
Club.create(name: 'Bærumsløkka', country_code: 'NO', league_name: 'Norwegian Lower Division')
Club.create(name: 'Bærumsløkka 2', country_code: 'NO', league_name: '-')
Club.create(name: 'Baesweiler', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Baeza', country_code: 'ES', league_name: 'Spanish Primera Andaluza Gr. 3')
Club.create(name: 'Bafa Belediyesi Zeytinspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Baffins Milton', country_code: 'GB', league_name: 'English Wessex League Premier Division')
Club.create(name: 'Bagarmossen Kärrtorp', country_code: 'SE', league_name: 'Swedish Fourth Division')
Club.create(name: 'Bağbaşı Zeytinköyspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Bağcılar Güneşlispor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bağcılarspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bağdeşen Gençlikspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bagheria', country_code: 'IT', league_name: 'Italian Promozione Sicilia Grp.B')
Club.create(name: 'Bagis Ultras BK', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'Bağıllıspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Baglan', country_code: 'UK', league_name: 'South Wales Alliance League Division One')
Club.create(name: 'Bağlar Bld.', country_code: 'TR', league_name: 'Turkish Regional Amateur League')
Club.create(name: 'Bağlarbaşı', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bağlarbaşıspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bağlarspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Bağlıkaya Gençlikspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bağlıkspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bağlumspor', country_code: 'TR', league_name: 'Turkish Regional Amateur League')
Club.create(name: 'Bagnacavallo', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bagnarese', country_code: 'IT', league_name: 'Italian Promozione Calabria Grp.B')
Club.create(name: 'Bagnères Luchon Sports', country_code: 'FR', league_name: 'French Regional Divisions')
Club.create(name: 'Bagnes', country_code: 'CH', league_name: 'Swiss Lower Division')
Club.create(name: 'Bagno di Romagna', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bagnolese', country_code: 'IT', league_name: 'Italian Eccellenza Emilia-Romagna Grp.A')
Club.create(name: 'Bagnolese (BS)', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bagnoli Irpino', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bagnolo (LE)', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bagshot', country_code: 'GB', league_name: 'Lower Leagues')
Club.create(name: 'Bahçecikspor', country_code: 'TR', league_name: 'Turkish Regional Amateur League')
Club.create(name: 'Bahçeköyspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Bahçespor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Bahlingen', country_code: 'DE', league_name: 'German Div. Lower')
Club.create(name: 'Baia Alassio', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Baiano', country_code: 'IT', league_name: 'Italian Promozione Campania Grp.C')
Club.create(name: 'Baião', country_code: 'PT', league_name: 'Portuguese Porto Elite Division Serie 2')
Club.create(name: 'Baiersdorf', country_code: 'DE', league_name: 'German Lower Division')
Club.create(name: 'Baikal', country_code: 'RU', league_name: 'Russian Fourth Division - Siberia')
Club.create(name: 'Baikonur', country_code: 'KZ', league_name: 'Kazakhstan First League')
Club.create(name: 'Baikonur U-18', country_code: 'KZ', league_name: 'Kazakhstan Lower League')
Club.create(name: 'Bailén', country_code: 'ES', league_name: 'Spanish Primera Andaluza Gr. 3')
Club.create(name: 'Bains-sur-Oust', country_code: 'FR', league_name: 'French Regional Divisions')
Club.create(name: 'Bairro da Argentina', country_code: 'PT', league_name: 'Portuguese Regional Divisions')
Club.create(name: 'Bairro da Misericórdia', country_code: 'PT', league_name: 'Portuguese Lower Regional Divisions')
Club.create(name: 'Bairro da Misericórdia Under 19s', country_code: 'PT', league_name: 'Portugal U19 Lower Divisions')
Club.create(name: 'Bairro do Valongo', country_code: 'PT', league_name: 'Portugal U19 Castelo Branco Division')
Club.create(name: 'Bairro FC', country_code: 'PT', league_name: 'Portuguese Lower Regional Divisions')
Club.create(name: 'Bairro N Srª Conceição', country_code: 'PT', league_name: 'Portuguese Lower Regional Divisions')
Club.create(name: 'Baiso Secchia', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Baiterek', country_code: 'KZ', league_name: 'Kazakhstan Second League Central Zone')
Club.create(name: 'Baizak', country_code: 'KZ', league_name: 'Taraz Open Championship')
Club.create(name: 'Baja', country_code: 'HU', league_name: 'Hungarian Lower Division')
Club.create(name: 'Bajcs', country_code: 'HU', league_name: 'Hungarian Lower Division')
Club.create(name: 'Bajen United FC', country_code: 'SE', league_name: 'Swedish Lower Division')
Club.create(name: 'Bajo Dora', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'BAK Bela Crkva', country_code: 'RS', league_name: 'Serbian Lower League')
Club.create(name: 'Bakhchysaray', country_code: 'RU', league_name: 'Crimean Premier League')
Club.create(name: 'Bakhmach', country_code: 'UA', league_name: "Ukrainian Reg Div - Chernigivs'ka oblast FD")
Club.create(name: 'Bakhmach-Yednist', country_code: 'UA', league_name: "Ukrainian Reg Div - Chernigivs'ka oblast HD")
Club.create(name: 'Bakhmaro', country_code: 'GE', league_name: 'Georgian Regional League Group A')
Club.create(name: 'Bakhmaro-2', country_code: 'GE', league_name: 'Samegrelo-Zemo Svaneti Open League')
Club.create(name: 'Bakhmut', country_code: 'UA', league_name: 'Ukrainian Reg Div - Donbas League')
Club.create(name: 'Bakhtrioni', country_code: 'GE', league_name: '-')
Club.create(name: 'Baki', country_code: 'AZ', league_name: 'Azeri Lower League')
Club.create(name: 'Bakia Cesenatico', country_code: 'IT', league_name: 'Italian Lower Division')
Club.create(name: 'Bakili', country_code: 'AZ', league_name: 'Azeri Lower League')
Club.create(name: 'Bakırköyspor', country_code: 'TR', league_name: 'Turkish Super Amateur League')
Club.create(name: 'Baklalıspor', country_code: 'TR', league_name: 'Turkish Local Amateur League')
Club.create(name: 'Bakovci', country_code: 'SI', league_name: 'Slovenian Lower League')
