default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { '5432' } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { '' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>

development:
  <<: *default
  database: firsttouch_devel_1 #CHANGE ME

test:
  <<: *default
  database: firsttouch_test #CHANGE ME

production:
  <<: *default
  database: firsttouch_prod #CHANGE ME

staging:
  <<: *default
  database: firsttouch_stage #CHANGE ME
