- Goalkeeper
- Sweeper (Centre)
- Defender (Right)
- Defender (Left)
- Defender (Centre)
- Wing-back (Right)
- Wing-back (Left)
- Defensive Midfielder (Centre)
- Midfielder (Right)
- Midfielder (Left)
- Midfielder (Centre)
- Attacking Midfielder (Centre)
- Winger (Right)
- Winger (Left)
- Second Striker (Centre)
- Striker (Centre)
