export const TOKEN_LOADING = 'TOKEN_LOADING';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';
export const TOKEN_CLEAR = 'TOKEN_CLEAR';

export const FEED_LOADING = 'FEED_LOADING';
export const FEED_SUCCESS = 'FEED_SUCCESS';
export const FEED_POSTED = 'FEED_POSTED';

export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';

export const NETWORK_LOADING = 'NETWORK_LOADING';
export const NETWORK_SUCCESS = 'NETWORK_SUCCESS';
export const NETWORK_UNFOLLOW = 'NETWORK_UNFOLLOW';
export const NETWORK_FOLLOW = 'NETWORK_FOLLOW';

export const INBOX_LOADING = 'INBOX_LOADING';
export const INBOX_SUCCESS = 'INBOX_SUCCESS';
export const INBOX_RELOAD = 'INBOX_RELOAD';

export const CONVO_LOADING = 'CONVO_LOADING';
export const CONVO_SUCCESS = 'CONVO_SUCCESS';
export const CONVO_RELOAD = 'CONVO_RELOAD';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FOLLOW = 'PROFILE_FOLLOW';
export const PROFILE_CONNECT = 'PROFILE_CONNECT';

export const SEARCH_RESULT_LOADING = 'SEARCH_RESULT_LOADING';
export const SEARCH_RESULT_SUCCESS = 'SEARCH_RESULT_SUCCESS';
export const SEARCH_RESULT_FLUSH = 'SEARCH_RESULT_FLUSH';

export const SEARCH_REPORT_LOADING = 'SEARCH_REPORT_LOADING';
export const SEARCH_REPORT_SUCCESS = 'SEARCH_REPORT_SUCCESS';
export const SEARCH_REPORT_FAILURE = 'SEARCH_REPORT_FAILURE';

export const UPLOADING_REPORT_FAILURE = 'UPLOADING_REPORT_FAILURE';
export const UPLOADING_REPORT_SUCCESS = 'UPLOADING_REPORT_SUCCESS';
export const UPLOADING_REPORT_LOADING = 'UPLOADING_REPORT_LOADING';

export const UPLOADING_REQUEST_FAILURE = 'UPLOADING_REQUEST_FAILURE';
export const UPLOADING_REQUEST_SUCCESS = 'UPLOADING_REQUEST_SUCCESS';
export const UPLOADING_REQUEST_LOADING = 'UPLOADING_REQUEST_LOADING';

export const SEARCH_REQUEST_LOADING = 'SEARCH_REQUEST_LOADING';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAILURE = 'SEARCH_REQUEST_FAILURE';

export const GET_CLUB_STRIPE_ACCOUNT_LOADING = 'GET_CLUB_STRIPE_ACCOUNT_LOADING';
export const GET_CLUB_STRIPE_ACCOUNT_SUCCESS = 'GET_CLUB_STRIPE_ACCOUNT_SUCCESS';
export const GET_CLUB_STRIPE_ACCOUNT_FAILURE = 'GET_CLUB_STRIPE_ACCOUNT_FAILURE';

export const CREATE_CLUB_STRIPE_ACCOUNT_LOADING = 'CREATE_CLUB_STRIPE_ACCOUNT_LOADING';
export const CREATE_CLUB_STRIPE_ACCOUNT_SUCCESS = 'CREATE_CLUB_STRIPE_ACCOUNT_SUCCESS';
export const CREATE_CLUB_STRIPE_ACCOUNT_FAILURE = 'CREATE_CLUB_STRIPE_ACCOUNT_FAILURE';

export const ORDER_REPORT_FAILURE = 'ORDER_REPORT_FAILURE';
export const ORDER_REPORT_SUCCESS = 'ORDER_REPORT_SUCCESS';
export const ORDER_REPORT_LOADING = 'ORDER_REPORT_LOADING';

export const BID_FAILURE = 'BID_FAILURE';
export const BID_SUCCESS = 'BID_SUCCESS';
export const BID_LOADING = 'BID_LOADING';
export const BID_CLEAR = 'BID_CLEAR';

export const BIDS_REQUEST_FAILURE = 'BIDS_REQUEST_FAILURE';
export const BIDS_REQUEST_SUCCESS = 'BIDS_REQUEST_SUCCESS';
export const BIDS_REQUEST_LOADING = 'BIDS_REQUEST_LOADING';

export const REPORT_FILES_UPLOAD_LOADING = 'REPORT_FILES_UPLOAD_LOADING';
export const REPORT_FILES_UPLOAD_SUCCESS = 'REPORT_FILES_UPLOAD_SUCCESS';
export const REPORT_FILES_UPLOAD_FAILURE = 'REPORT_FILES_UPLOAD_FAILURE';
export const REPORT_FILE_FAILURE = 'REPORT_FILE_FAILURE';
export const REPORT_FILE_SUCCESS = 'REPORT_FILE_SUCCESS';
export const USER_IMPORT_SUCCESS = 'USER_IMPORT_SUCCESS';
