export const TOKEN_LOADING = 'TOKEN_LOADING';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';
export const TOKEN_CLEAR = 'TOKEN_CLEAR';

export const FEED_LOADING = 'FEED_LOADING';
export const FEED_SUCCESS = 'FEED_SUCCESS';
export const FEED_POSTED = 'FEED_POSTED';

export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';

export const NETWORK_LOADING = 'NETWORK_LOADING';
export const NETWORK_SUCCESS = 'NETWORK_SUCCESS';
export const NETWORK_UNFOLLOW = 'NETWORK_UNFOLLOW';
export const NETWORK_FOLLOW = 'NETWORK_FOLLOW';

export const INBOX_LOADING = 'INBOX_LOADING';
export const INBOX_SUCCESS = 'INBOX_SUCCESS';
export const INBOX_RELOAD = 'INBOX_RELOAD';

export const CONVO_LOADING = 'CONVO_LOADING';
export const CONVO_SUCCESS = 'CONVO_SUCCESS';
export const CONVO_RELOAD = 'CONVO_RELOAD';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FOLLOW = 'PROFILE_FOLLOW';
export const PROFILE_CONNECT = 'PROFILE_CONNECT';

export const SEARCH_RESULT_LOADING = 'SEARCH_RESULT_LOADING';
export const SEARCH_RESULT_SUCCESS = 'SEARCH_RESULT_SUCCESS';

export const NEW_REPORT_FAILURE = 'NEW_REPORT_FAILURE';
export const NEW_REPORT_SUCCESS = 'NEW_REPORT_SUCCESS';